theme: jekyll-theme-minimal
baseurl: "/j200"
permalink: /:categories/:title.html

exclude: ["notes"]
highlighter: rouge

title : Data Bootcamp -- Mapping
description: J200, Fall 2018
logo: assets/logo-blue-retina.png

# author :
##  name    : Amanda Hickman
##  email   : amanda@velociraptor.info
##  github  : ucb-dataj
